//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotCopper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinanceCrawlerEntities : DbContext
    {
        public FinanceCrawlerEntities()
            : base("name=FinanceCrawlerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<HotCopper_Authors> HotCopper_Authors { get; set; }
        public DbSet<HotCopper_Market_data> HotCopper_Market_data { get; set; }
        public DbSet<HotCopper_Posts> HotCopper_Posts { get; set; }
        public DbSet<HotCopper_Threads> HotCopper_Threads { get; set; }
    }
}
