//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotCopper
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotCopper_Threads
    {
        public long Identity { get; set; }
        public string Stock { get; set; }
        public string Tags { get; set; }
        public string Subject { get; set; }
        public string First_Poster { get; set; }
        public Nullable<long> Num_of_Views { get; set; }
        public Nullable<System.DateTime> Begin_Date { get; set; }
        public string Last_Poster { get; set; }
        public string Last_Post { get; set; }
        public Nullable<long> Num_of_Posts { get; set; }
    }
}
