//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotCopper
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotCopper_Authors
    {
        public long Identity { get; set; }
        public string Name { get; set; }
        public Nullable<long> Num_of_Posts { get; set; }
        public Nullable<long> Likes_Received { get; set; }
        public Nullable<long> Following { get; set; }
        public Nullable<long> Followers { get; set; }
        public string Following_List { get; set; }
        public string Followers_List { get; set; }
        public Nullable<long> Num_of_Posts_in_calendar_month { get; set; }
        public string Following_Stocks { get; set; }
    }
}
