//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotCopper
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotCopper_Market_data
    {
        public long Identity { get; set; }
        public string Tag { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> High { get; set; }
        public Nullable<decimal> Low { get; set; }
        public Nullable<decimal> Open { get; set; }
        public Nullable<decimal> Last { get; set; }
        public Nullable<decimal> Market_Price { get; set; }
        public Nullable<decimal> Volume__Millions_ { get; set; }
        public Nullable<decimal> Value__Millions_ { get; set; }
        public Nullable<decimal> Market_Cap__Billions_ { get; set; }
    }
}
